Repository Programming-Engineering-Pmi-33/Drink_water, pull requests merged in 2020-10, with the labels that each got.

#26 UML Діаграма
  Requirements.docx
Labels: documentation

#30 Database source
  DataOutput.cs
  Database/Database
  Documentary/Admin.jpg
  Documentary/Requirements.docx
  Documentary/User.jpg
  Model/ActivityTime.cs
  Model/DailyStatistic.cs
  Model/Notifications.cs
  Model/Statistic.cs
  Model/User.cs
  Model/UserParameters.cs
  Model/dfkg9ojh16b4rdContext.cs
  Requirements.docx
Labels: enhancement

#27 Sophia branch
  TestFunctions.cs
  UnitTest1.cs
  use_case.jpg
Labels: enhancement

#25 Misha branch
  DataOutput.cs
  Database/Database
  Documentary/Admin.jpg
  Documentary/Requirements.docx
  Documentary/User.jpg
  Model/ActivityTime.cs
  Model/DailyStatistic.cs
  Model/Notifications.cs
  Model/Statistic.cs
  Model/User.cs
  Model/UserParameters.cs
  Model/dfkg9ojh16b4rdContext.cs
  Requirements.docx
Labels: enhancement

#43 Виправила UML схему
  Database_schema.png
  Functions&Test/TestFunctionsStatistics.cs
  Functions&Test/UnitTest1.cs
Labels: help wanted
